# Spring Boot Application Port Configuration
server.port=8080

# MQTT Broker Configurations
# URL of the Mosquitto MQTT Broker running locally
mqtt.broker.url=tcp://localhost:1883

# Client IDs for MQTT publisher and subscriber connections
mqtt.client.subscriber.id=iot-monitor-subscriber
mqtt.client.publisher.id=iot-device-publisher-simulator

# The MQTT topic pattern we subscribe to (Stage 2: devices/+)
mqtt.topic.pattern=devices/+

# Logging level configuration for the project
logging.level.com.example.iot=INFO
